#!/usr/bin/bash

# Idea from here: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

echo "(Re)processing in PDFLaTeX..."
pdflatex vsego-cv-prog.tex

echo
echo "Uploading to vsego.org..."
scp -q vsego-cv-prog.pdf vsegoorg@vsego.org:www/

echo
echo "Pushing to Github..."
